from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


HEADER_FILL = PatternFill("solid", fgColor="244F43")
SECTION_FILL = PatternFill("solid", fgColor="DDEBE5")
THIN = Side(style="thin", color="B9C5C0")


def generate_workbook(payload: dict, destination: Path) -> Path:
    validate_payload(payload)
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Expense Map"
    sheet.freeze_panes = "A8"
    sheet.sheet_view.showGridLines = False

    sheet.merge_cells("A1:F1")
    sheet["A1"] = "SYNTHETIC EXPENSE MAP"
    sheet["A1"].font = Font(size=18, bold=True, color="FFFFFF")
    sheet["A1"].fill = HEADER_FILL
    sheet["A1"].alignment = Alignment(horizontal="center")
    sheet.row_dimensions[1].height = 32

    metadata = (
        ("Unit", payload["unit"]["name"]),
        ("Code", payload["unit"]["code"]),
        ("Period", payload["period"]),
        ("Prepared for", "Public portfolio demonstration"),
    )
    for row, (label, value) in enumerate(metadata, start=3):
        sheet.cell(row, 1, label).font = Font(bold=True, color="315A4D")
        sheet.cell(row, 2, value)
        sheet.merge_cells(start_row=row, start_column=2, end_row=row, end_column=6)

    headers = ("#", "Document", "Supplier", "Issue date", "Category", "Amount")
    header_row = 8
    for column, value in enumerate(headers, start=1):
        cell = sheet.cell(header_row, column, value)
        cell.fill = SECTION_FILL
        cell.font = Font(bold=True, color="244F43")
        cell.alignment = Alignment(horizontal="center")
        cell.border = Border(bottom=THIN)

    first_data_row = header_row + 1
    for offset, document in enumerate(payload["documents"]):
        row = first_data_row + offset
        values = (
            offset + 1,
            document["reference"],
            document["supplier"],
            date.fromisoformat(document["issued_on"]),
            document["category"],
            Decimal(str(document["amount"])),
        )
        for column, value in enumerate(values, start=1):
            cell = sheet.cell(row, column, value)
            cell.border = Border(bottom=Side(style="hair", color="D9E0DD"))
            cell.alignment = Alignment(vertical="top", wrap_text=True)
        sheet.cell(row, 4).number_format = "yyyy-mm-dd"
        sheet.cell(row, 6).number_format = '"$"#,##0.00'

    total_row = first_data_row + len(payload["documents"])
    sheet.merge_cells(start_row=total_row, start_column=1, end_row=total_row, end_column=5)
    sheet.cell(total_row, 1, "TOTAL")
    sheet.cell(total_row, 1).font = Font(bold=True)
    sheet.cell(total_row, 1).alignment = Alignment(horizontal="right")
    sheet.cell(total_row, 6, f"=SUM(F{first_data_row}:F{total_row - 1})")
    sheet.cell(total_row, 6).font = Font(bold=True, color="244F43")
    sheet.cell(total_row, 6).number_format = '"$"#,##0.00'
    for cell in sheet[total_row]:
        cell.fill = SECTION_FILL
        cell.border = Border(top=THIN)

    widths = (6, 22, 27, 14, 20, 15)
    for index, width in enumerate(widths, start=1):
        sheet.column_dimensions[get_column_letter(index)].width = width
    sheet.auto_filter.ref = f"A{header_row}:F{total_row - 1}"
    sheet.print_area = f"A1:F{total_row}"
    sheet.print_title_rows = f"1:{header_row}"
    sheet.page_setup.fitToWidth = 1
    sheet.sheet_properties.pageSetUpPr.fitToPage = True

    validation = workbook.create_sheet("Validation")
    validation.append(("Check", "Result"))
    validation.append(("Synthetic data only", "PASS"))
    validation.append(("Required fields", "PASS"))
    validation.append(("Document count", len(payload["documents"])))
    validation.append(("Generated by", "rebral-map-generator-case-study"))
    validation.column_dimensions["A"].width = 28
    validation.column_dimensions["B"].width = 38
    for cell in validation[1]:
        cell.fill = HEADER_FILL
        cell.font = Font(color="FFFFFF", bold=True)

    destination.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(destination)
    return destination


def validate_payload(payload: dict) -> None:
    if not isinstance(payload, dict) or not isinstance(payload.get("unit"), dict):
        raise ValueError("unit object is required")
    if not payload["unit"].get("name") or not payload["unit"].get("code"):
        raise ValueError("unit name and code are required")
    if not payload.get("period"):
        raise ValueError("period is required")
    documents = payload.get("documents")
    if not isinstance(documents, list) or not documents:
        raise ValueError("at least one document is required")
    required = {"reference", "supplier", "issued_on", "category", "amount"}
    for document in documents:
        if not isinstance(document, dict) or required - set(document):
            raise ValueError("every document must contain all required fields")
        date.fromisoformat(document["issued_on"])
        if Decimal(str(document["amount"])) < 0:
            raise ValueError("amount cannot be negative")
